#!/bin/bash
target="`zenity --file-selection --directory`"
if [[ -z "$target" ]]; then
	echo "No target directory, aborting..."
	exit 1
fi

for var in "$@"
do
	filename="`stripextension \"$var\"`"
	xarchiver -x "$target/`basename \"$filename\"`" "$var"
	echo xarchiver -x "$target/`basename \"$filename\"`" "$var" >> /dev/shm/tmp/eat.log
done
