#!/bin/bash
target="`zenity --file-selection --directory`"
if [[ -z "$target" ]]; then
	echo "No target directory, aborting..."
	exit 1
fi

for var in "$@"
do
	filename=`echo "$var" | rev | cut -d. -f2- | rev`
	xarchiver -x "$target/`basename \"$filename\"`" "$var"
done
