#!/bin/sh
if [ $# -eq 1 ]; then
	streamlink --player-no-close --player "mpv" --player-args "--keep-open" --hls-timeout 9999 --hls-segment-threads 10 "$1" "best" > /dev/null 2>&1 &
	exit
else
	echo usage:
	echo "$0 url"
fi
exit 1
